services:
  - type: web
    name: tuskers-cricket-club
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tuskers-cricket-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: tuskers-cricket-db
    databaseName: tuskers_cricket
    user: tuskers_user